language: python
python:
- '3.6'
node_js:
- 6.11.5
install:
- python setup.py install
- npm install -g grunt-cli
- npm install
script:
- grunt mini
- grunt test
deploy:
  provider: heroku
  app: developingwithstyle
  skip_cleanup: true
  api_key:
    secure: "bFFVkpZgcBokjQ0Cdr1RFFHEAPYhYQYbLx4rc4gchbZbkc77XS+YQCgzmY6BsT3VgfyKTdNVTh8gsXFKe8Hiwz3P+Jj52MIppdLy6G1MkRJXO240GstLwNuXwF5PxU/bBYQrA48EoynKTCWz/Jg5iukCtkb6r0UMzTa4WEphkXmR2NUkWeODlUIKdbSxZydv8Lctcv0uVYRj7FavNfhP06KiSHam1IzYUMxivTVNuup1xRP1n3o1uj6mQpjnINn4GGR44Txg5pJRK/PCHvpZaCm3wwWQ2ur/glZwWNq/RSyIea5wa1M4lRxeZAcEfzmqgoqq8mvka51jPS2vshldvkTXp+mNhichuI4jNYjQ4uDXCKjRIGTuBjk14OZU37osb1ihD/Pnrh4wjrqWkHofTmcaOYR3gEJhMO/YR7dI00jXBPlFXOdoQmcjZN1B/V4ew7Cjz+6ijeVOFUdTxHItXGw2R24cP7ylisIAjwytfOjyiLMy1MaFxd2+JADTeBfhtyj2jeI44gPU1tQy3BzAvbnR9DFbtdoSe9huhhN/fQLrROYvF2e3kd0Drx63KNa/4AjIBDmv6og5pqu7O/IoMDFeOv4zEJCS4kGOc47zabwPlwKmDW91c9YKhUzY0MqbDhGl1sSk+gEeD2cHES0+YjrGAiSSjECzGZnc4neinTE="
  on:
    branch: deployment
