language: python
python:
- '3.6'
node_js:
- 6.11.5
install:
- python setup.py install
- npm install -g grunt-cli
- npm install
script:
- grunt mini
- grunt test
deploy:
  provider: heroku
  app: developingwithstyle
  skip_cleanup: true
  api_key:
    secure: JW+cCvLJL0cOmASOxaa0DStWQo8k3DFPHtwuohbxyCj3qNoX4vjE2WY8ChrCN6DQzgADAqgSM+bavd9dU+A2YLe11XGrI4IILtftU+c4CGoh4oe+rSmHQTWgu2iQwALDGlTHv+gHIn7hsf1kgonL0VTBrP/Yi+FkLv4S+u+5/nmz3dn7VeVCYsB4xl7plbLR8EC768U1ZG30ZsTcGj/vPDFWinZDgVe9/zsZ7glkyOZfRCPYBxjieRzjBotOueKGVtgglvA+K5CVxKdhYGfhiTh2WrpHBF0wqotk5Fej/izO/FMf2l1rOaGsFiSqTgHHDwHmJiDHXIyXhc7Fc+KiaqTaPqcVxLyH6yKp3tbx7teOV8tHSDe5Ad7/YKVoWfv8kF4Dr8vJpkxSG9z3IZTggR7eH1FAsnT+7OGkbNZH9K5QUpEeLLl2pfj7ZlJcrh2vRKf9iXMqCQT0vxCArTkaPfT6Sr3Itp0+0S0K3QJO3gXuE+MVLV9pRc91e4HvRfz0W7bjur3CQe7pJLMy3HcrcL0+91OeNoPvldahUAXtKp4pMMSm7/bqR+HQGX6cb4n04a8LbfB3h0dHK2UWfOeReibTM044ioIRMC/rp9Hrx55m94r/RUdRw/0mbEWrZwex6ALSVyt3tKuz2JBTnFeBXbe+GjXpvSqZQ7+dYWuc9oY=
  on:
    branch: deployment
