language: python
python:
  - "2.7"

node_js:
  - "6.11.5"
# command to install dependencies
install:
  - pip install --user -r requirements.txt
  - npm install -g grunt-cli
  - npm install
# command to run tests
script:
  - grunt test