language: python
python:
  - "3.6"

node_js:
  - "6.11.5"
# command to install dependencies
install:
  - pip install --upgrade pip
  - python setup.py install
  - npm install -g grunt-cli
  - npm install
# command to run tests
script:
  - grunt test

