language: python
python:
- '3.6'
node_js:
- 6.11.5
install:
- python setup.py install
- npm install -g grunt-cli
- npm install
script:
- grunt mini
- grunt test
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: j3bbDSscc62hDDGX/HRjQKkqJNBpV4Yipsp9Ke3V+8m9cYGLFRA4cfzso59fffh9od51AVbFkF1uLGJeVJHJYPcfUJf9EbZvz6cBFSUinSNrG+b/rwBSxwDmgpqolsYZCe/iA3yAKqs2rK6UWi+sqlXSH9BfYQULHPjNwsHxAYXT+8kP0rBr3InRaFeVdJn7qg7L64L2Cwrl+08qiFKWKDty+xV9dCy10tiL1PuBMj48I2h2f821JGqcJcKshPufdTJOI2yKea7Femn/f5DkeoiWHaytEfqRDBY8Z37YnEICs6WdhU+9dcFAzvgL6M0ppwTX4VfTh2gitlUWOh0BpRaJ2v/igH3BMhLBvJuavLMPMi5agAH76NTN8M5UHKg4LrnTd89LV3ix58gRG2pL3Rm3IBeUI3OQjh4Y08KalZ1ICA1bOSUgLKwXITRpliL6ao26ZkRpzWdYRMB+YcmBHr8NqU+nMRX4CEaY1t9GAM6dZPuDeoNfcNsH/YjT3S7Tr58rYohFTVOk/JPiq/B1gD7w1Uv8HFsTeMeVqBMqs/ZJ3jObn2lVg+rPQy06C6xM1XiL+/issp03l/TLOJM4Y6W4dGhVgytfITvSeSPiIhLM5MYSkWkzocUn5I2NkKywM3i/YOlyOyNjlfSEP0iBtu7TRIbDeX4vMYyWhioqM6s=
  app: developingwithstyle
  on:
    repo: flyiniggle/developingwithstyle
    branch: deployment
